# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: workflow_dispatch
  # schedule:
  #   - cron: '0 13 * * 3'
  # push:

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      POST_TWEET: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install igraph system dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-i686-glpk mingw-w64-i686-libxml2 mingw-w64-i686-gmp mingw-w64-x86_64-glpk mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gmp

      - name: Setup Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: palaeoverse-community/rphylopic, local::.

      - name: Render Rmarkdown files
        env:
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_APP_TOKEN: ${{ secrets.TWITTER_APP_TOKEN }}
          TWITTER_APP_TOKEN_SECRET: ${{ secrets.TWITTER_APP_TOKEN_SECRET }}
        run: |
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' README.Rmd

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md man/figures/R_gems.png man/figures/phylopic_a_pack.png -m 'Re-build Readme file' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
